### ISSUE TITLE
create releases

### ISSUE THREAD

**Issue by CvH** [linuxwhatelse/visualization.pictureit#13]
It would be great if some recent version would be released and the tags are pushed. 
Currently the most recent version is 2 years old.

Also pls stay in line with all other kodi addons from the naming schema, this would make packaging a lot easier, tx. 
1.2.3-Leia
2.3.4-Matrix
...

**Comment by AlwinEsch** [comment]
Have created some releases, was gone down a bit on this git, Sorry!
