### ISSUE TITLE
Download links not working

### ISSUE THREAD

**Issue by j2ghz** [linuxwhatelse/visualization.pictureit#5]
Download links here as well as on http://forum.kodi.tv/showthread.php?tid=236514 are not working. LinuxWhatElse repo downloads okay but it contains just google play music

**Comment by tadly** [comment]
The visualization is linux only so this might be the actual issue?
Are you using windows or osx by any change?

**Comment by j2ghz** [comment]
missed `LINUX ONLY (for now)`, sorry
