### ISSUE TITLE
doesn't build anymore

### ISSUE THREAD

**Issue by CvH** [linuxwhatelse/visualization.pictureit#9]
```
[2/4] Building CXX object CMakeFiles/visualization.pictureit.dir/src/pictureit.cpp.o
FAILED: CMakeFiles/visualization.pictureit.dir/src/pictureit.cpp.o
/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.0-devel/toolchain/bin/x86_64-libreelec-linux-gnu-g++  -DBUILD_KODI_ADDON -DHAS_GL -DHAS_OPENGL -Dvisualization_pictureit_EXPORTS -I/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/include/kodi -I../lib/kissfft -march=x86-64 -m64 -fomit-frame-pointer -Wall -pipe -Os -mmmx -msse -msse2 -mfpmath=sse -std=c++11 -Os -DNDEBUG -fPIC   -D_LINUX -DTARGET_POSIX -DTARGET_LINUX -D_GNU_SOURCE -DHAVE_LINUX_MEMFD=1 -DHAVE_MKOSTEMP=1 -DHAVE_SSE=1 -DHAVE_SSE2=1 -DHAVE_SSE3=1 -DHAVE_SSSE3=1 -DHAVE_SSE4_1=1 -MD -MT CMakeFiles/visualization.pictureit.dir/src/pictureit.cpp.o -MF CMakeFiles/visualization.pictureit.dir/src/pictureit.cpp.o.d -o CMakeFiles/visualization.pictureit.dir/src/pictureit.cpp.o -c ../src/pictureit.cpp
../src/pictureit.cpp:1:10: fatal error: xbmc_vis_dll.h: No such file or directory
 #include "xbmc_vis_dll.h"
          ^~~~~~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.
```
likely not updated for latest K18

**Comment by tadly** [comment]
Ssssshhhhhhh.... let sleeping dogs lie :)

But in all seriousness, yes I'm aware and seeing as I won't get [this](https://github.com/linuxwhatelse/PictureIt) done anytime soon (if ever) I did actually start porting this mess of project to the new interface some time ago as I require it myself ':D

Haven't had a lot of time finishing it though :/
IIRC, the port is complete in theory but in practice segfaults which I never figured out why and than I left it.

I'll commit what I have to another branch for now and try and fix it sometime before Lei is officially out

**Comment by CvH** [comment]
okay, I just asked because I thought about dropping it at LibreELEC if this add-on is abandoned
nice to see that is actually still maintained 👍

**Comment by tadly** [comment]
eh, **maintained** is... optimistic :D

But unless something similar from a dev who actually knows what he's doing comes along I kinda have to keep this up :)

[leia branch](https://github.com/linuxwhatelse/visualization.pictureit/tree/leia) is up and once that one works will be merged into master.
Build goes through but the addon will segfault as already mentioned

**Comment by CvH** [comment]
at least something ;)
tx for your efforts

**Comment by tadly** [comment]
Goooooooooood lord that took some doing.
With f08d0aa6d5f80cfa95a24adca48be15e333ca8e0 the vis works again **IF** OpenGL < 3.2.

For a lot of systems this means setting `MESA_GL_VERSION_OVERRIDE=3.1` is required.
This is because with OGL >=3.2 the fixed function pipeline has been removed and I am not going to implement shaders anytime soon if at all.
I still don't understand what I'm doing and getting this to work was way to painful 🙄

PRs are welcome of course 🙃

**Comment by CvH** [comment]
Tx, i test it asap

**Comment by AlwinEsch** [comment]
With https://github.com/linuxwhatelse/visualization.pictureit/pull/10 it works on all OS and newest Kodi 19
